name: Bug Report
description: Report a bug you found
title: "[Bug Title here] "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea #description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea #reproduce
    attributes:
      label: How can we reproduce this bug?
      description: Are there any specific steps you had to take in order to trigger the bug, and what is the expected behavior we should expect?
      placeholder: Kindly elaborate.
    validations:
      required: true

  - type: textarea #desktop info
    attributes:
      label: Desktop Information (Optional)
      description: Please provide the desktop configuration (OS, Browser, dependency version, etc.)
      placeholder: Type here.

  - type: dropdown #urgent
    attributes:
      label: Urgency (Optional)
      description: How urgent do you think it is to fix this bug?
      options:
        - Low priority
        - Medium priority
        - High priority

  - type: checkboxes
    id: terms
    attributes:
      label: 'Record'
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have checked the existing issues
          required: true
        - label: I'm a GSSoC'23 contributor
        - label: I want to work on this issue